sudo: true
os:
- linux
dist: xenial
language: python
python:
- 3.6
services:
  - docker
env:
  global:
    - IMAGE_NAME=ximanz/freqtrade
install:
- cd build_helpers && ./install_ta-lib.sh ${HOME}/dependencies/; cd ..
- export LD_LIBRARY_PATH=${HOME}/dependencies/lib:$LD_LIBRARY_PATH
- export TA_LIBRARY_PATH=${HOME}/dependencies/lib
- export TA_INCLUDE_PATH=${HOME}/dependencies/lib/include
- pip install -r requirements-dev.txt
- pip install -e .
jobs:

  include:
    - stage: tests
      script:
      - pytest --random-order --cov=freqtrade --cov-config=.coveragerc freqtrade/tests/
      # Allow failure for coveralls
      - coveralls || true
      name: pytest
    - script:
      - cp config.json.example config.json
      - freqtrade --datadir freqtrade/tests/testdata backtesting
      name: backtest
    - script:
      - cp config.json.example config.json
      - freqtrade --datadir freqtrade/tests/testdata hyperopt -e 5
      name: hyperopt
    - script: flake8 freqtrade scripts
      name: flake8
    - script:
      # Test Documentation boxes -
      # !!! <TYPE>: is not allowed!
      - grep -Er '^!{3}\s\S+:' docs/*; test $? -ne 0
      name: doc syntax
    - script: mypy freqtrade scripts
      name: mypy

    - stage: docker
      if: branch in (master, develop, feat/improve_travis) AND (type in (push, cron))
      script:
        - build_helpers/publish_docker.sh
      name: "Build and test and push docker image"
notifications:
  email:
    recipients:
      - ximanz@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
cache:
  pip: True
  directories:
    - $HOME/dependencies
